export const USER_LOG_IN = "Users/USER_LOG_IN";
export const PARKING_ADDED = "Parkings/PARKING_ADDED";
export const PARKING_DELETED="Parkings/PARKING_DELETED";
export const FETCH_PARKINGS_LAUNCH = "Parkings/FETCH_PARKINGS_LAUNCH";
export const FETCH_PARKINGS_PROPERLY = "Parkings/FETCH_PARKINGS_PROPERLY";
export const FETCH_PARKINGS_ERROR = "Parkings/FETCH_PARKINGS_ERROR";
